before_script:
  - echo "yes" | sudo add-apt-repository ppa:markhannon/ppa && sudo apt-get install libiniparser-dev
language: c
compiler:
  - gcc
  - clang
script: mkdir build && cd build && cmake ../ && make && make install
