branches:
  only:
    - master
before_install:
  - sudo apt-get install -qq check 
language: c
compiler:
  - gcc
  - clang
before_script:
  - mkdir build
  - cd build
  - cmake ../
script:
  - make
after_script:
  - make test
