before_script:
  - add-apt-repository ppa:markhannon/ppa && apt-get install libiniparser-dev
language: c
compiler:
  - gcc
  - clang
script: mkdir build && cd build && cmake ../ && make && make install
